name: furniture_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  equatable: ^2.0.7
  firebase_crashlytics: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  logger: ^2.6.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
